admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    defaults:  { _locale: en }
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    defaults:  { _locale: en }
