# Application bundles

CoreBundle:
    resource: "@JDACoreBundle/Resources/config/routing.yml"
    prefix:   /

ZeegaUserBundle:
    resource: "@ZeegaUserBundle/Resources/config/routing.yml"
    prefix:   /
    
# Authorization

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Admnistration

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    defaults:  { _locale: en } 

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    defaults:  { _locale: en } 
    
#maint:
#    pattern:   /
#    defaults:  { _controller: JDACoreBundle:Maintenance:index}


