parameters:
#    zeega_user.example.class: Zeega\UserBundle\Example

services:
    zeega_user_registration.form.type:
        class: Zeega\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: zeega_user_registration}
#    zeega_user.example:
#        class: %zeega_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
