parameters:
#    zeega_data.example.class: Zeega\DataBundle\Example

services:
#    zeega_data.example:
#        class: %zeega_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
