# src/Zeega/\CoreBundle\/Resources/config/doctrine/Media.orm.yml
Zeega\DataBundle\Entity\Media:
    type: entity
    table: media
    oneToOne:
       item:
         targetEntity: Item
         mappedBy: media
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        format:
            type: string
            length: 15
            nullable: true
        bit_rate:
            type: integer
            size: 10
            nullable: true
        duration:
            type: integer
            length: integer
            nullable: true
        width:
            type: integer
            length: 10
            nullable: true
        height:
            type: integer
            length: 10
            nullable: true
        aspect_ratio:
            type: float
            nullable: true
        