# src/Zeega/\CoreBundle\/Resources/config/doctrine/Metadata.orm.yml
Zeega\DataBundle\Entity\Metadata:
    type: entity
    table: metadata
    oneToOne:
       item:
         targetEntity: Item
         mappedBy: metadata
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        archive:
            type: string
            length: 50
            nullable: true
        license:
            type: string
            length: 50
            nullable: true
        thumbnail_url:
            type: string
            length: 100
            nullable: true
        attributes:
            type: array
            nullable: true
        location:
            type: string
            length: 100
            nullable: true