# src/Zeega/\CoreBundle\/Resources/config/doctrine/Tag.orm.yml
Zeega\DataBundle\Entity\Tag:
    type: entity
    table: tag
    repositoryClass: Zeega\DataBundle\Repository\TagRepository
    oneToMany:
        item:
            targetEntity: ItemTags
            mappedBy: tag
            joinColumn:
                name: id
                referencedColumnName: tag_id
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            size: 20
            nullable: false
        date_created:
            type: datetime
            nullable: false
        description:
            type: text
            nullable: true
            