# src/Zeega/\CoreBundle\/Resources/config/doctrine/TagCorrelation.orm.yml
Zeega\DataBundle\Entity\TagCorrelation:
    type: entity
    table: tagcorrelation
    repositoryClass: Zeega\DataBundle\Repository\TagCorrelationRepository
    manyToOne:
        tag:
            targetEntity: Tag
        tag_related:
            targetEntity: Tag
    id:
        tag:
            associationKey: true
        tag_related:
            associationKey: true
    fields:
        correlation_index:
            type: float
            nullable: false
