# src/Zeega/UserBundle/Resources/config/doctrine/User.orm.yml
Zeega\DataBundle\Entity\User:
    type: entity
    table: zuser
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        display_name:
            type: string
            length: 255
            nullable: true
        bio:
            type: text
            nullable: true
        thumb_url:
            type: string
            length: 255
            nullable: true
        created_at:
            type: datetime
            nullable: true
        user_type:
            type: string
            length: 50
            nullable: true
        location:
            type: string
            length: 140
            nullable: true
        location_latitude:
            type: float
            length: 10
            nullable: true
        location_longitude:
            type: float
            length: 10
            nullable: true
        background_image_url:
            type: string
            length: 255
            nullable: true
        dropbox_delta:
            type: string
            length: 255
            nullable: true
        idea:
            type: text
            nullable: true
        api_key:
            type: string
            length: 25
            nullable: true

    indexes:
        user_type_index:
            columns: [user_type]